### ISSUE TITLE
[Peer Review] - Search & Roulette Ignore Category

### ISSUE THREAD

**Issue by mackenzieleach** [mackenzieleach/screwthereview#115]
We got the following during peer review: "Search and roulette functions ignore search term/category, eg. searching for “art” or “museum” gives restaurants instead of experiences related to the searched term." 

I believe we know this may be an issue with a keyword on Search entered by a user that is not a Yelp category, but since Roulette is using the official category list it should be returning an experience matching the category.

**Comment by lulup2** [comment]
done for roulette
