### ISSUE TITLE
Netlify - Server Issues

### ISSUE THREAD

**Issue by mackenzieleach** [mackenzieleach/screwthereview#49]
The server is throwing errors on the Netlify deployment and preventing the experience results from rendering. The rendering works locally, but it looks like the server may need to be configured to run on our URL.

**Comment by luuuk** [comment]
Can you give more detail / upload some screenshots of this issue?

**Comment by mackenzieleach** [comment]
If you navigate to https://screwthereview.netlify.app/search and click "Screw that Review", it takes you to the result page which does not show an experience result. The functionality does work locally. 
![ResultBug](https://user-images.githubusercontent.com/66976423/117599086-ff37e600-b0fd-11eb-9c54-da3b61f5557c.JPG)

**Comment by mackenzieleach** [comment]
Resolved this by adding a server whitelist.
