### ISSUE TITLE
[Bug] Screw the Review - Search Filter Highlighting

### ISSUE THREAD

**Issue by nys99** [mackenzieleach/screwthereview#99]
**Describe the Bug**
Please provide a clear and concise description of the bug you encountered.

Unable to select multiple filters when searching. For example, I could choose a distance or a price filter, but I could not select both. 

**Reproduce the Bug?**
What steps should be taken to reproduce the bug? ("Go to...", "Click on...", etc.)

Try to select the single $ and 5mi on the search filters. 

**Expected Behavior**
Please provide a clear and concise description of what behavior you expected.

Both the $ and 5mi should be highlighted yellow.

**Screenshots**
Please add any screenshots of the bug you encountered.

**Desktop:**

Chrome, on Ubuntu 20.04

**Smartphone:**

**Additional Context**
Any other additional context for the bug?

**Comment by mackenzieleach** [comment]
This is already an open issue under @rachelye1, will leave her assigned here.

**Comment by mackenzieleach** [comment]
They're a little slow if you click through them very fast, but it's unlikely a user would select and deselect these continually and quickly.
